[project]
name = "HyperBoxLauncher"
version = "0.1.0"
description = "Launcher for my minecraft project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.2",
    "dotenv>=0.9.9",
    "psutil>=7.1.3",
    "pywebview>=6.1",
]
